services:
  - type: web
    name: quizlive
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLOUDFLARE_ACCOUNT_ID
        value: 49ddc127c82369828887b2f9abbf914d
      - key: PUBLIC_BASE_URL
        value: https://quizlive-27vz.onrender.com
